let DB=null, MASTER=null, SAVE=null, CURRENT={placeId:null,subName:null};
async function init(){DB=await(await fetch('data.json')).json();MASTER=await(await fetch(DB.masterFile||'ZWDB_MASTER_V8_FINAL.json')).json();const local=localStorage.getItem('z_generation_save_v9');SAVE=local?JSON.parse(local):buildInitialSave();normalizeSave();renderStatus()}
function buildInitialSave(){const rel={};(MASTER.characters||[]).forEach(c=>{rel[c.id]={name:c.name,category:c.category||((['wen_xubai','qi_lin','xie_chengyu','pei_ji'].includes(c.id))?'maleLead':'core'),age:c.age,height:c.height||'未知',occupation:c.occupation||'未知',affection:c.affectionToPlayer||0,relation:c.relationToPlayer||'未结识',met:!!c.metPlayer,visibleStats:c.visibleStats||{},currentLocation:c.currentLocation||'未知'}});return{state:structuredClone(DB.state),relationships:rel,business:{Deadline:{productLine:4200,endorsement:1800,industryNetwork:2200,governmentSupport:1200,publicOpinion:1900,marketShare:1600,cash:3000000000,monthlyRevenue:40000000,fixedCosts:18000000,variableCosts:12000000,netProfit:10000000,lastMonth:{monthlyRevenue:40000000,fixedCosts:18000000,variableCosts:12000000,netProfit:10000000}}},history:[],monthlyReports:[]}}
function normalizeSave(){const s=SAVE.state;s.year=s.year||1;s.month=s.month||1;s.week=s.week||1;s.actionsLeft=Number.isFinite(s.actionsLeft)?s.actionsLeft:3;s.visitedPlacesThisWeek=s.visitedPlacesThisWeek||[];s.brandTier=s.brandTier||'小众';s.brandScore=s.brandScore||14500;s.reputation=s.reputation||s.brandScore}
function saveLocal(){localStorage.setItem('z_generation_save_v9',JSON.stringify(SAVE))}
function renderStatus(){const s=SAVE.state;const top=document.getElementById('aiTopStatus'),badge=document.getElementById('aiCompanyBadge');if(top)top.textContent=`Z年${s.month}月 第${s.week}周｜行动 ${s.actionsLeft}/3`;if(badge)badge.textContent=`Deadline｜${s.brandTier}｜声望 ${Math.round(s.reputation||s.brandScore||0)}`}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');renderStatus()}
function openOverlay(type){showPage('overlayPage');const t={phone:'手机',favor:'好感',industry:'行业',settings:'设置'};document.getElementById('overlayTitle').textContent=t[type]||'功能';if(type==='phone')renderPhone();if(type==='favor')renderFavor();if(type==='industry')renderIndustry();if(type==='settings')renderSettings()}
function renderPhone(){document.getElementById('overlayContent').innerHTML=`<div class="grid2"><button onclick="phoneAI('短信')">短信</button><button onclick="phoneAI('电话')">电话</button><button onclick="phoneAI('朋友圈')">朋友圈</button><button onclick="phoneAI('Z世界新闻')">Z世界新闻</button></div><div id="phoneOutput" class="storyBox">选择功能后，AI会根据当前联系人、关系状态和世界新闻生成内容。</div>`}
function renderFavor(){const rels=Object.values(SAVE.relationships||{}),male=rels.filter(r=>r.category==='maleLead'),core=rels.filter(r=>r.category!=='maleLead');const card=r=>`<div class="charCard"><h3>${r.name}</h3><div class="charMeta">年龄：${r.age||'未知'}　身高：${r.height||'未知'}　职业：${r.occupation||'未知'}</div><span class="tag">好感 ${r.affection||0}</span><span class="tag">关系：${r.relation||'未结识'}</span><span class="tag">位置：${r.currentLocation||'未知'}</span></div>`;document.getElementById('overlayContent').innerHTML=`<div class="sectionTitle">男主</div>${male.map(card).join('')||'<div class="storyBox">暂无男主数据</div>'}<div class="sectionTitle">核心人物</div>${core.map(card).join('')||'<div class="storyBox">暂无核心人物数据</div>'}`}
function renderIndustry(){const b=SAVE.business.Deadline;const stats={公司等级:SAVE.state.brandTier,声望:SAVE.state.reputation,现金:b.cash,月营收:b.monthlyRevenue,固定成本:b.fixedCosts,可变成本:b.variableCosts,净利润:b.netProfit,产品线:b.productLine,代言人:b.endorsement,业内人脉:b.industryNetwork,政界支持:b.governmentSupport,舆论:b.publicOpinion,市场占据:b.marketShare};document.getElementById('overlayContent').innerHTML=Object.entries(stats).map(([k,v])=>`<div class="statCard"><span>${k}</span><b>${format(v)}</b></div>`).join('')+`<div class="grid2"><button onclick="companyAction('研发新品')">研发新品</button><button onclick="companyAction('媒体公关')">媒体公关</button><button onclick="companyAction('代言人谈判')">代言人谈判</button><button onclick="companyAction('董事会会议')">董事会会议</button><button onclick="companyAction('查看其他公司')">其他公司数据</button><button onclick="companyAction('月度预判')">月度预判</button></div><div id="companyOutput" class="storyBox"></div>`}
function renderSettings(){document.getElementById('overlayContent').innerHTML=`<div class="storyBox">快捷AI助手。你可以询问当前局势、公司策略、关系分析、下一步行动建议。</div><textarea id="askInput" placeholder="例如：分析Deadline本月最应该做什么"></textarea><div class="grid2"><button onclick="askGM()">询问AI</button><button onclick="resetSave()">重置本地存档</button></div><div id="askOutput" class="storyBox"></div>`}
function format(v){return typeof v==='number'?v.toLocaleString('zh-CN'):v}
async function enterPlace(id){if(!DB.places[id])return alert('地点不存在:'+id);const consumed=consumeActionForPlace(id);renderStatus();openPlace(id);if(SAVE.state.actionsLeft===0&&consumed)setTimeout(()=>advanceWeek(),350)}
function consumeActionForPlace(placeId){const visited=SAVE.state.visitedPlacesThisWeek||[];if(visited.includes(placeId))return false;if(SAVE.state.actionsLeft<=0){advanceWeek();return false}visited.push(placeId);SAVE.state.visitedPlacesThisWeek=visited;SAVE.state.actionsLeft-=1;saveLocal();return true}
async function advanceWeek(){SAVE.state.week+=1;SAVE.state.actionsLeft=3;SAVE.state.visitedPlacesThisWeek=[];if(SAVE.state.week>4){SAVE.state.week=1;SAVE.state.month+=1;if(SAVE.state.month>12){SAVE.state.month=1;SAVE.state.year+=1}await monthlySummary()}else{saveLocal();renderStatus();openSystemEvent('新一周开始',`进入Z年${SAVE.state.month}月第${SAVE.state.week}周。行动次数已恢复为3。`)}}
async function monthlySummary(){openSystemEvent('月度结算中','AI正在生成本月公司数据、营收支出、管理变动、其他公司升降与Z世界大新闻。');await generateAI('deadline','创始人办公室','month_summary','进行月度结算：公司数据对比上月、营收支出、公司管理变动、代言人签约、其他公司数据升降、Z世界大新闻汇总。')}
function openPlace(id){CURRENT.placeId=id;const p=DB.places[id];let html=`<h2>${p.name}</h2><div class="desc">选择进入区域。同一地点内多次互动不消耗行动点。</div>`;Object.entries(p.sub).forEach(([name,obj])=>{html+=`<div class="item" onclick="openSub('${id}','${esc(name)}')"><b>${name}</b><small>${obj.desc}</small></div>`});html+=`<div class="item aiBtn" onclick="generateAI('${id}',null,'location')">AI推演此地当前局势</div><div class="item close" onclick="closeSheet()">返回地图</div>`;const sheet=document.getElementById('sheet');sheet.innerHTML=html;sheet.style.display='block'}
function esc(s){return String(s).replaceAll("'","\\'")}function closeSheet(){document.getElementById('sheet').style.display='none'}
function openSub(pid,sub){CURRENT={placeId:pid,subName:sub};const place=DB.places[pid],obj=place.sub[sub];closeSheet();document.getElementById('event').classList.add('active');document.getElementById('eventTitle').textContent=`${place.name} · ${sub}`;document.getElementById('eventText').textContent=`${obj.desc}\n\n请选择AI推演方向，或在底部自由输入行动。`;document.getElementById('choices').innerHTML=`<div class="choice aiBtn" onclick="generateAI('${pid}','${esc(sub)}','event')">AI生成此处剧情</div><div class="choice" onclick="generateAI('${pid}','${esc(sub)}','business')">公司经营/商战</div><div class="choice" onclick="generateAI('${pid}','${esc(sub)}','romance')">人物互动/恋爱线</div><div class="choice" onclick="generateAI('${pid}','${esc(sub)}','crisis')">突发事件</div>`;document.getElementById('result').innerHTML=''}
function openSystemEvent(title,text){document.getElementById('event').classList.add('active');document.getElementById('eventTitle').textContent=title;document.getElementById('eventText').textContent=text;document.getElementById('choices').innerHTML='';document.getElementById('result').innerHTML=''}
async function generateAI(placeId,subName,mode,freeInput=null,targetBox=null){const place=DB.places[placeId]||{},sub=subName&&place.sub?place.sub[subName]:null;if(!targetBox){document.getElementById('event').classList.add('active');closeSheet();document.getElementById('result').innerHTML='<div class="loading">AI正在推演Z世界...</div>'}const payload={mode,placeId,placeName:place.name,subName,subDescription:sub?sub.desc:'',state:SAVE.state,business:SAVE.business,relationships:SAVE.relationships,recentHistory:SAVE.history.slice(-12),freeInput};try{const res=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(targetBox){document.getElementById(targetBox).textContent=(data.output&&data.output.story)||data.error||JSON.stringify(data);return}renderAI(data)}catch(e){document.getElementById('result').innerHTML=`<div class="result">AI接口失败：${e.message}</div>`}}
function renderAI(data){if(!data||data.error){document.getElementById('result').innerHTML=`<div class="result">AI错误：${data?.error||'未知'}</div>`;return}const out=data.output||data;document.getElementById('eventTitle').textContent=out.title||'Z世界事件';document.getElementById('eventText').textContent=out.story||out.text||JSON.stringify(out,null,2);window.__choices=Array.isArray(out.choices)?out.choices:[];document.getElementById('choices').innerHTML=window.__choices.map((c,i)=>`<div class="choice" onclick="chooseAI(${i})">${typeof c==='string'?c:c.text}</div>`).join('');applyEffects(out.effects||{});if(out.relationshipUpdates)applyRelationshipUpdates(out.relationshipUpdates);SAVE.history.push({time:new Date().toISOString(),title:out.title,story:out.story,effects:out.effects,relationshipUpdates:out.relationshipUpdates});if(SAVE.history.length>120)SAVE.history=SAVE.history.slice(-120);saveLocal();renderStatus();document.getElementById('result').innerHTML='<div class="result">本地存档已更新。</div>'}
function chooseAI(i){const c=window.__choices[i];document.getElementById('freeInput').value=typeof c==='string'?c:c.text;sendFreeAction()}function sendFreeAction(){const input=document.getElementById('freeInput');const text=input.value.trim();if(!text)return;input.value='';document.getElementById('result').innerHTML='<div class="loading">AI正在根据你的输入继续推演Z世界...</div>';generateAI(CURRENT.placeId||'deadline',CURRENT.subName,'free_action',text)}
function applyEffects(e={}){if(e.state)Object.assign(SAVE.state,e.state);const b=SAVE.business.Deadline;if(e.business)for(const[k,v]of Object.entries(e.business)){if(typeof v==='number'&&typeof b[k]==='number')b[k]+=v;else b[k]=v}if(e.relationships)applyRelationshipUpdates(e.relationships)}function applyRelationshipUpdates(updates={}){for(const[id,vals]of Object.entries(updates)){SAVE.relationships[id]=SAVE.relationships[id]||{name:id,affection:0,relation:'未结识',met:false};const r=SAVE.relationships[id];if(typeof vals.affection==='number')r.affection=(r.affection||0)+vals.affection;if(vals.relation)r.relation=vals.relation;if(typeof vals.met==='boolean')r.met=vals.met;if(vals.visibleStats)r.visibleStats={...(r.visibleStats||{}),...vals.visibleStats}}}
function closeEvent(){document.getElementById('event').classList.remove('active');renderStatus()}function phoneAI(type){generateAI('private',null,'phone_'+type,`打开手机功能：${type}`,'phoneOutput')}function companyAction(type){generateAI('deadline','创始人办公室','company_'+type,`执行公司操作：${type}`,'companyOutput')}function askGM(){const t=document.getElementById('askInput').value.trim();if(!t)return;generateAI('deadline','创始人办公室','gm_question',t,'askOutput')}function resetSave(){localStorage.removeItem('z_generation_save_v9');location.reload()}init();
